### PR TITLE
feat(migration): Add vote question controller

### LINKED ISSUE #15: Migrate vote controller
Migrate this controller https://github.com/wizeline/wize-q-back/blob/develop/controllers/votes.js#L9 to Prisma

### PR DESCRIPTION
**Pull request by AldoDominguezWizeline**
#### What does this PR do?
It adds the voteQuestion controller

#### Where should the reviewer start?
- controllers/questionVotes/voteQuestion.js
- tests/integration/questionVotes.test.js

#### How should this be manually tested?
The integration tests are covering this while the vote functionality gets implemented in the UI using the controller.

#### What are the relevant tickets?
(Link to issues, related PR, JIRA issues, etc.)
Closes #15

### CODE REVIEW

**Review by albertcastaned — APPROVED** [review]
LGTM 👍 , this should allow dislikes in the future right?

**Comment by AldoDominguezWizeline** [comment]
@albertcastaned Not yet, it's the same current logic in the app where you can add your vote to the question or retire said vote later, I wanted to implement the current like system (no dislikes yet) to test a little bit, then add the dislike, what do you think? 👀

**Comment by albertcastaned** [comment]
> 

Ah okay no worries, no need for dislikes in the scope of this ticket yet. I thought the delete of Vote was meant to be for dislike, didnt see the legacy controller. LGTM!

**Comment by AldoDominguezWizeline** [comment]
@albertcastaned Got it, thanks a lot!

**Pull request merged**
