### PR TITLE
chore(tests): add cypress test for creation of questions

### LINKED ISSUE #92: Cypress - Add create question E2E test

### PR DESCRIPTION
**Pull request by albertcastaned**
#### What does this PR do?
- Adds cypress test for creation of question as anonymous user
- Tweaks home page questions to run faster

#### How should this be manually tested?
1. Run `npm run test:cypress:run`
2. Verify GIthub Actions for this PR pass

#### What are the relevant tickets?
(Link to issues, related PR, JIRA issues, etc.)
Closes #92

### CODE REVIEW

**Comment by GeorginaFraire** [comment]
I'm getting this error. 
Screen Shot 2022-11-22 at 10 07 46

**Comment by GeorginaFraire** [comment]
This is the video. Mexico City is not selected as location.

https://user-images.githubusercontent.com/97203617/204666933-c1bbe6f6-8149-4a86-b5ef-dda7a33e6f76.mp4


If I move the test that validates the toast message after validating if the new question is shown in the list, that test passed.
I think it's because of the time it takes while validating the locations, that's why I get the error in both.
The only thing that I don't get it, is why is selecting a different city.

Screen Shot 2022-11-29 at 17 02 39

https://user-images.githubusercontent.com/97203617/204669024-67b1ad1f-5502-47ce-a366-59634125a4d9.mp4

**Comment by albertcastaned** [comment]
> I'm getting this error. Screen Shot 2022-11-22 at 10 07 46

Weird how it doesn't happen on my local or in Github Actions 🤔 maybe the order varies on the machine for some reason? What I could do is see if I can make the city name dynamic (always select the first option and grab the text), and not hardcode it to Mexico City

**Comment by albertcastaned** [comment]
Closing since we are migrating to Playwright 😅

**Pull request closed without merging**
