### PR TITLE
feat(migration): createComment controller

### LINKED ISSUE #14: Migrate createComment controller

### PR DESCRIPTION
**Pull request by albertcastaned**
#### What does this PR do?
- Adds createComment controller migration.
- Adds migration to set createdAt field for comment default

#### Where should the reviewer start?
- See new createComment function

#### How should this be manually tested?
- Only testable through integration tests at the moment.
- Worth testing in your local if migrations are applied without issues with `npx prisma migrate dev`. Just in case

#### What are the relevant tickets?
(Link to issues, related PR, JIRA issues, etc.)
Closes #14

### CODE REVIEW

**Comment by GeorginaFraire** [comment]
Could you please add a default value for the updatedAt column in the Comment table?

**Comment by GeorginaFraire** [comment]
> > Could you please add a default value for the updatedAt column in the Comment table?
> 
> Is this okay? Or is it missing something?
> 
> https://github.com/wizeline/wize-q-remix/blob/24906a194f143b46c8d2702537e4d42f3317a361/prisma/schema.prisma#L53
> 
> I think it was added on #45

I mean this value ` @default(now()).`
Something like this 
Screen Shot 2022-10-25 at 10 52 18

The @updatedAt attribute is used when the record is modified, then the value of the column is automatically changed without specifying any value.

**Comment by albertcastaned** [comment]
> > > Could you please add a default value for the updatedAt column in the Comment table?
> > 
> > 
> > Is this okay? Or is it missing something?
> > https://github.com/wizeline/wize-q-remix/blob/24906a194f143b46c8d2702537e4d42f3317a361/prisma/schema.prisma#L53
> > 
> > I think it was added on #45
> 
> I mean this value ` @default(now()).` Something like this Screen Shot 2022-10-25 at 10 52 18
> 
> The @updatedAt attribute is used when the record is modified, then the value of the column is automatically changed without specifying any value.

Ooh okay will do!

**Comment by albertcastaned** [comment]
Done 😃 @GeorginaFraire

**Review by GeorginaFraire — APPROVED** [review]
LGTM 🎉

**Pull request merged**
