### PR TITLE
feat(migration): migrate questionDetail component (retrive data) 

### LINKED ISSUE #5: Question Detail Migration

### PR DESCRIPTION
**Pull request by GeorginaFraire**
#### What does this PR do?
- Initial migration for the QuestionDetail Component (just to show the information)

#### How should this be manually tested?
(List of steps to reproduce, corroborate or tests to run. Write this section clear enough so that external users can also follow it and test the fix.)
1. Login
2. Click in any question
3. Verify that you can see:
         - The question,
         - The number of likes and comments 
         -  Pin question (if the question has the attribute)
         -  Who create the question
         - The department.
4. Click on the `Back` button to verify its functionality
5. 
#### What are the relevant tickets?
Closes #5 

#### Screenshots
Screen Shot 2022-10-12 at 19 03 10

👀 Until this point, we can't see the comments or do all the actions related to this page because we don't have all the controller for each action.

### CODE REVIEW

**Comment by albertcastaned** [comment]
Updating with master branch

**Comment by albertcastaned** [comment]
LGTM 👍 
image

Noticed, pinning redirects to home which is an oversight from my previous PR 🙇 will fix later

As you mentioned most actions are not available, but I believe showing the Answer is possible right now https://github.com/wizeline/wize-q-remix/blob/master/app/controllers/questions/getQuestionById.js#L7. Showing comments looks like is not in that controller but should be a quick fix.

We can do that in another ticket/PR if you prefer

**Review by albertcastaned — APPROVED** [review]

**Comment by GeorginaFraire** [comment]
Now we can see the answer. 

Screen Shot 2022-10-13 at 18 05 09

@albertcastaned Can you review it again, please? Thank you!

**Review by albertcastaned — APPROVED** [review]
Looks good to me, and thank you for the pin change 🙏 Amazing job ✨

**Pull request merged**
