### PR TITLE
feat: add creation of embeddings with openai

### LINKED ISSUE #242: Create an embedding generation script or process
Create an embedding generation script that generates the embedding vectors from our questions and answers and stores it in our backend (#240 and #241).

# Requirements

- This will need to use OpenAPI's API, and need a private token
- For local testing, and to avoid pounding OpenAPI, maybe locally it could in turn use [gtr-t5-large](https://huggingface.co/sentence-transformers/gtr-t5-large). There is a tutorial on [how to use it](https://til.simonwillison.net/python/gtr-t5-large) by [Simon Willison](https://twitter.com/simonw). But then the script would need to be in python and write to our database storage outside of our regular nodejs backend.

# Prior example work

- [This script](https://github.com/supabase/supabase/blob/54d39d4958575e5b58aa1d5d2a02db863ab4673c/apps/docs/scripts/generate-embeddings.ts) does the same, and is explain in [this video](https://youtu.be/Yhtjd7yGGGA?t=359).

### PR DESCRIPTION
**Pull request by albertcastaned**
#### What does this PR do?
- Adds controllers and schema updates to support embeddings.
- Adds OpenAI integration of node. Currently the API key is not set, pending from IT. But not necesarry for merge.

#### How should this be manually tested?
- Clone this branch and verify prisma migrations work on your local.
- Answer a question and verify there are no errors

#### What are the relevant tickets?
Closes #242

### CODE REVIEW

**Comment by GeorginaFraire** [comment]
HI @albertcastaned  got this error: 
Screen Shot 2023-10-24 at 13 18 48

I had to install _esbuild-linux-64_ with `npm i esbuild-linux-64`
Is this okay? 

After doing it, I was able to run the project as usual

**Review by GeorginaFraire — COMMENTED** [review]
HI @albertcastaned  got this error: 
Screen Shot 2023-10-24 at 13 18 48

I had to install _esbuild-linux-64_ with `npm i esbuild-linux-64`
Is this okay? 

After doing it, I was able to run the project as usual

**Comment by albertcastaned** [comment]
> HI @albertcastaned got this error: Screen Shot 2023-10-24 at 13 18 48
> 
> I had to install _esbuild-linux-64_ with `npm i esbuild-linux-64` Is this okay?
> 
> After doing it, I was able to run the project as usual

Did you use `nvm use` before the npm install? Gonna take a look

**Comment by GeorginaFraire** [comment]
> > HI @albertcastaned got this error: Screen Shot 2023-10-24 at 13 18 48
> > I had to install _esbuild-linux-64_ with `npm i esbuild-linux-64` Is this okay?
> > After doing it, I was able to run the project as usual
> 
> Did you use `nvm use` before the npm install? Gonna take a look

Yes, also I verified the migrations and the dependencies, running `npm install`

**Comment by albertcastaned** [comment]
> > > HI @albertcastaned got this error: Screen Shot 2023-10-24 at 13 18 48
> > > I had to install _esbuild-linux-64_ with `npm i esbuild-linux-64` Is this okay?
> > > After doing it, I was able to run the project as usual
> > 
> > 
> > Did you use `nvm use` before the npm install? Gonna take a look
> 
> Yes, also I verified the migrations and the dependencies, running `npm install`

Can't reproduce the issue locally 🤔 . Can you upload your local package.json diff with this new dependency as a commit to this? The GH Actions build and test jobs doesn't seem to fail though.

**Comment by GeorginaFraire** [comment]
Here is a video. Maybe I'm doing something wrong.

https://github.com/wizeline/wize-q-remix/assets/97203617/0baa3db9-fbdd-418a-919d-2b442f3e4f5c

**Comment by albertcastaned** [comment]
Maybe npm version? I have:
```
> npm -v
9.8.1
```

Jobs seem to fail with your changes though 😕 @GeorginaFraire

**Comment by GeorginaFraire** [comment]
Yes! You're right.
I updated my npm version and reverted the changes and everything works fine.

**Review by GeorginaFraire — APPROVED** [review]
🎉

**Pull request merged**
