### PR TITLE
feat: update about/contact page 

### LINKED ISSUE #52: Update about/contact page
Update deprectated links and information, such as Github repo point to Remix repository.

### PR DESCRIPTION
**Pull request by AlonsoMtzG**
#### What does this PR do?
- updates repo link
- update bullet points style (Things to Keep in Mind When Asking a Question)

#### Where should the reviewer start?
- In app/routes/about.jsx

#### How should this be manually tested?
1. Make sure the new link on the About page redirects you to the wize-q-remix repo
2. Check the blue bullet pts are displayed correctly
3. 🎉 

#### What are the relevant tickets?
Closes #52 

#### Screenshots
Captura de Pantalla 2022-10-26 a la(s) 13 10 07

### CODE REVIEW

**Review by albertcastaned — APPROVED** [review]
LGTM, maybe we can add the #wizeq-2022 channel near the repo links? What do you think

**Comment by AlonsoMtzG** [comment]
> LGTM, maybe we can add the #wizeq-2022 channel near the repo links? What do you think

Yes! Maybe like this(?) 👇🏼 @albertcastaned 
Captura de Pantalla 2022-10-26 a la(s) 14 15 06

**Comment by albertcastaned** [comment]
> > LGTM, maybe we can add the #wizeq-2022 channel near the repo links? What do you think
> 
> Yes! Maybe like this(?) 👇🏼 @albertcastaned Captura de Pantalla 2022-10-26 a la(s) 14 15 06

LGTM!

**Comment by albertcastaned** [comment]
Think it should be this instead https://wizeline.slack.com/archives/C031D9DP7C2, to not point to a specific message

**Pull request merged**
